version: '3.7'
services:
  nginx:
    build:
      args:
        VERSION: 1.25.3
      context: .
      dockerfile: ./Dockerfile
      target: nginx
    depends_on:
      - php-fpm
    ports:
      - "9001:80"
  php-fpm:
    build:
      args:
        VERSION: 8.3
      context: .
      dockerfile: ./Dockerfile
      target: php-fpm
    command: sh -c 'php-fpm'