name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v3

    - name: Build the Docker images
      run: DOCKER_DEFAULT_PLATFORM="linux/arm64/v8" docker compose build

    - name: Tag images
      run: |
        docker tag immodemo/nginx:latest ${{ secrets.CONTAINER_REGISTRY_URL }}/nginx:${{ secrets.VERSION }}
        docker tag immodemo/php-fpm:latest ${{ secrets.CONTAINER_REGISTRY_URL }}/php-fpm:${{ secrets.VERSION }}

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PWD }}

    - name: Push images to container registry
      run: |
        docker push ${{ secrets.CONTAINER_REGISTRY_URL }}/nginx:${{ secrets.VERSION }}
        docker push ${{ secrets.CONTAINER_REGISTRY_URL }}/php-fpm:${{ secrets.VERSION }}