name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PWD }}

    - name: Nginx - Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64/v8
        build-args: VERSION=${{ secrets.NGINX_VERSION }}
        target: nginx
        push: true
        tags: ${{ secrets.CONTAINER_REGISTRY_URL }}/nginx:${{ secrets.VERSION }}

    - name: PHP-FPM - Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64/v8
        build-args: VERSION=${{ secrets.PHP_FPM_VERSION }}
        target: php-fpm
        push: true
        tags: ${{ secrets.CONTAINER_REGISTRY_URL }}/php-fpm:${{ secrets.VERSION }}